### ISSUE TITLE
bug with % percent sign in url

### ISSUE THREAD

**Issue by Leonidaz** [paulmillr/exoskeleton#106]
this is the same issue as exists for backbone:  https://github.com/jashkenas/backbone/issues/3426 

history uses `decodeURI`, then router uses `decodeURIComponent` to extract params, if there was a `%` percent sign encoded as `%25` in the url, the `decodeURIComponent` would blow up.

Here's a preliminary fix ( https://github.com/braddunbar/backbone/commit/7ed58e4d39265d7100e62659b654dc6182d1e434) by the backbone guys which replaced `%25` with `%2525` before `encodeURI` is applied in history on the whole url, so that `%25` stays encoded for `decodeURIComponent` in the router.

**Comment by akre54** [comment]
When we figure out a solution at jashkenas/backbone, we'll bring it over here as well. No sense in creating needless incompatibilities before then.

**Comment by Leonidaz** [comment]
cool, didn't know you guys are so tight with backbone :)  it's a good thing.

**Comment by akre54** [comment]
Yep. I work on (and use) both projects.

**Comment by Leonidaz** [comment]
@akre54 now that the commit landed in backbone, any eta when you'll be updating exoskeleton?  thank you!
