### ISSUE TITLE
PhantomJS Backbone.History Issues

### ISSUE THREAD

**Issue by MatthewCallis** [paulmillr/exoskeleton#107]
When trying to run a spec through PhantomJS I am running into an issue that doesn't happen with Backbone proper:

```
mocha-phantomjs --setting localToRemoteUrlAccessEnabled=true --setting webSecurityEnabled=false test/index.html --hooks ./hooks.js --timeout 25000
TypeError: 'undefined' is not a function (evaluating 'this.checkUrl.bind(this)')

  file:///Users/matthew/dokidoki/_site/assets/backbone/exoskeleton.js:1570
  file:///Users/matthew/dokidoki/_site/assets/backbone/exoskeleton.js:1769
  file:///Users/matthew/dokidoki/_site/assets/backbone/exoskeleton.js:23
  file:///Users/matthew/dokidoki/_site/assets/backbone/exoskeleton.js:1771
```

**Comment by akre54** [comment]
PhantomJS has a known issue in that [it doesn't support `Function.protype.bind`](https://code.google.com/p/phantomjs/issues/detail?id=522). We [pollyfill it in one of our test helpers](https://github.com/paulmillr/exoskeleton/blob/0.7.0/test/vendor/runner.js#L72-L98).

I'm not sure what you're running into though, the tests seem to be running fine for me.

**Comment by MatthewCallis** [comment]
Okay thanks!
