### ISSUE TITLE
Which is the preferred View library?

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [paulmillr/exoskeleton#113]
Hi.

Since there are problems with using the Chaplin:
```javascipt
TypeError: f.utils.delegate is not a function
```
caused by the **Backbone.utils.delegate** and **Backbone.utils.undelegate** functions that are absent which substitute for the Chaplin would you recommend?

**Comment by akre54** [comment]
We got rid of `utils.delegate` and `utils.undelegate` in favor of sticking them on `View.prototype` like Backbone does. Chaplin hasn't been updated to support the latest view hooks (see my pull in https://github.com/chaplinjs/chaplin/pull/780).
