### ISSUE TITLE
Integration with marionette

### ISSUE THREAD

**Issue by bmiller59** [paulmillr/exoskeleton#114]
Hello. I was reviewing this thread regarding allowing the use of exoskeleton with marionette: https://github.com/marionettejs/backbone.marionette/pull/768. It seemed to suggest that there was some positive resolution. 

I have just tried to replace backbone with exoskeleton in a requirejs based app and am still getting errors saying underscore and jquery not found. 

Is there a way use exoskeleton instead of jquery and underscore with marionette, perhaps even in a beta form? Please describe how integrate them.

Thanks for this great project.

**Comment by akre54** [comment]
Marionette still depends on Underscore and jQuery, unfortunately. You'll have to take it up with them.

**Comment by bmiller59** [comment]
Thanks. I could you see you tried to persuade them of the benefits.
