### ISSUE TITLE
ExosJS + RequireJS without jQuery and Underscore

### ISSUE THREAD

**Issue by Inateno** [paulmillr/exoskeleton#116]
I'm trying to load exosekeleton with RequireJS and saw that:

```javascript
if (typeof define === 'function' && define.amd) {
    define(['underscore', 'jquery', 'exports'], function(_, $, exports) {
      root.Backbone = root.Exoskeleton = factory(root, exports, _, $);
    });
}
```

I didn't see anything inside RequireJS to ignore these modules, my current solution is to replace it by

```javascript
if (typeof define === 'function' && define.amd) {
    define(['underscore', 'jquery', 'exports'], function(_, $, exports) {
      root.Backbone = root.Exoskeleton = factory(root, exports, root._, (root.jQuery || root.Zepto || root.ender || root.$));
    });
}
```

Maybe we could add an if/else a window or define options value, and test it to let user choice amd without jquery and co ?
```
if ( define.amd.jQuery === false || window.usejQuery === false )
  // load without jQuery+
else
  // load with jQuery+
```

?

Bests

**Comment by akre54** [comment]
Use the [`empty`](http://requirejs.org/docs/optimization.html#empty) config in your requirejs paths. Exoskeleton should do the right thing and ignore jQuery.

**Comment by Inateno** [comment]
It seems that empty is only for build (http://requirejs.org/docs/optimization.html#empty)

There is nothing about "empty depencie" in the documentation (I checked it before post here, anyway) and trying this way throw me an error: "ERR_UNKNOWN_URL_SCHEME"

Maybe an issue on RequireJS himself ?
