### ISSUE TITLE
No hashbang fallback or fallforward

### ISSUE THREAD

**Issue by JoannesJ** [paulmillr/exoskeleton#118]
Exoskeleton doesn't fallback to hasbangs when running on IE9.
It also doesn't convert hasbangs to regular addresses when pushState is supported.

**Comment by akre54** [comment]
That's correct, we only support browsers with window.pushState.

If you need support for older browsers, give Backbone a try (or add it in via a plugin).

**Comment by JoannesJ** [comment]
Too bad, I'll see if I can get something working for myself.

Btw, I don't know if I skipped over anything, but you might want to put that under the "Drop-in replacement section" or something. Might save a few the frustration.

**Comment by akre54** [comment]
I'll add it to the differences section.
