### ISSUE TITLE
Switch to grunt?

### ISSUE THREAD

**Issue by Boycce** [paulmillr/exoskeleton#122]
Would you consider switching to `grunt` as `make` is a unix command, leaving windows user in the dark regarding custom builds. Grunt works great across all os's.

**Comment by akre54** [comment]
I personally don't like grunt as a build tool. It may make sense to switch to ES6 modules rather than naiive concatenation at some point, but even a vanilla JS build script may work here.

**Comment by paulmillr** [comment]
???

**Comment by Boycce** [comment]
Hmm why close, I think the a cross platform build is a relevant feature request idea.

**Comment by paulmillr** [comment]
see http://brunch.io, grunt is a terrible choices for pretty much anything

**Comment by Boycce** [comment]
Yeah sweet, or since it's only concatenation, vanilla js can do also.
