### ISSUE TITLE
Object returned by changedAttributes lacks .prototype methods.

### ISSUE THREAD

**Issue by malisbad** [paulmillr/exoskeleton#125]
When I call `model.changedAttributes()`, the object that is returned lacks typical object methods such as `hasOwnProperty`.

`typeof` returns the type "object", the inspector recognizes it as an object and parses it correctly.

The object seems to have no prototype.

**Comment by akre54** [comment]
Correct. The object is created using [`Object.create(null)`](https://github.com/paulmillr/exoskeleton/blob/51d760c10c6a6024110da3324f20383f62b45b04/exoskeleton.js#L621). It's a feature, and an intentional deviation from Backbone, in Exoskeleton. Is something breaking for you?

**Comment by justinffs** [comment]
One of the things that breaks is using backbone validation with exoskeleton.  Right here https://github.com/thedersen/backbone.validation/blob/master/src/backbone-validation.js#L76

**Comment by malisbad** [comment]
It breaks when I'm trying to look and see if something specific has changed. It works well because it returns a boolean so I can do something like `model.changeAttributes().hasOwnProperty('someKey')`.

It's very readable when using control flow statements.

**Comment by akre54** [comment]
@malisbad try using `model.hasChanged('someKey')` instead. 

@justinffs Keep in mind that [an object is not a hash](http://www.devthought.com/2012/01/18/an-object-is-not-a-hash/). The author of that library should be using `hasOwnProperty.call(obj, prop)` (or even better `_.has(obj, prop)`) instead. I'd open a bug there.
