### ISSUE TITLE
Promote exoskelton

### ISSUE THREAD

**Issue by joshspivey** [paulmillr/exoskeleton#56]
I did the same thing a year ago that exoskeleton is doing but its not as mature and its privatized bye my work. Some people are voting me down on stackoverlow not believing the performance from it promote exoskeleton and vote me back up!.

http://stackoverflow.com/questions/11458436/angular-js-backbone-js-or-which-has-better-performance/20154118?noredirect=1#comment30042146_20154118

**Comment by avesus** [comment]
:+1:
